### ISSUE TITLE
Bug with cake on consume quests

### ISSUE THREAD

**Issue by Pexep** [titanlabs-mc/battle-pass#390]
### Describe the bug

For consume quests where cakes score, left-click cakes when food-bar points are missing score the quest (it's not with a left click that we consume cakes but with a right click).

### How to reproduce

1. Make a consume quest with "none" variable for example
2. Drain food-bar
3. Left-click a placed cake

You don't consume the cake but the quest scores.

**Comment by Erdi-GitHub** [comment]
Fixed, wait for the next update
