### ISSUE TITLE
Reward with underscores

### ISSUE THREAD

**Issue by GothkittyGirl** [titanlabs-mc/battle-pass#616]
### Describe the bug

only want to let you guys know about a command reward problem with reward and underscores the command rewards doesnt work in something has a _ in it like **'crate givekey vote_crate %player%'** i has to be changed to **'crate givekey votecrate %player%'**

### How to reproduce

'crate givekey vote_crate %player%' as a command reward

### Screenshots / Videos

none because no error just doesnt give the item

**Comment by KPGTB** [comment]
Hey! Are you sure that the problem is caused by underscore in command? Maybe your crate is just named `votecrate`, because command is executed properly, so I think that it's problem of crates plugin

**Comment by GothkittyGirl** [comment]
i never get email about these sorry but i think it had to do with the other plugin because i found a issue with the  command in it and worked later i believe
