### ISSUE TITLE
Not working on Folia 1.21.1

### ISSUE THREAD

**Issue by Tudorhc5** [titanlabs-mc/battle-pass#617]
### Describe the bug

The plugin does not load on Folia 1.21.1, even tho it says `folia-supported: true` in `plugin.yml`

### How to reproduce

Try to load the plugin on a Folia 1.21.1 Server.

### Server Log

https://paste.helpch.at/hayoyifuxu.php

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update
