### ISSUE TITLE
The plugin executes database operations on the server thread

### ISSUE THREAD

**Issue by 1mSaw** [titanlabs-mc/battle-pass#619]
### Describe the bug

The problem is that the plugin runs database operations on the server thread. Database operations are thread-blocking tasks.

### How to reproduce

https://spark.lucko.me/qgYxNkgBG9

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/21958531-cd6d-4ae8-9e91-07cae7511faf)

### Server Log

https://spark.lucko.me/qgYxNkgBG9

**Comment by KPGTB** [comment]
Hey! Fix will be available in one of the next updates
