### ISSUE TITLE
Player Placed

### ISSUE THREAD

**Issue by wundertraume** [titanlabs-mc/battle-pass#620]
### Describe the bug

The players are creating a farm to perform a Combat Pass. What does it mean? Those tasks where you need to break the blocks if the player has put them and after restarting the server they are considered as if the player did not put them

### How to reproduce

1) Place any blocks
2) Stop server (restart)
3) Break this blocks
4) Check progress

// Check video

### Screenshots / Videos

https://youtu.be/IJWfY2-QeXs

**Comment by KPGTB** [comment]
Hey! I improved block cache system. Fix of your problem will be available in one of the next updates
