### ISSUE TITLE
%total_progress%, %required_progress% do not work correctly as placeholder for any other placeholders

### ISSUE THREAD

**Issue by GoneWhiteBunny** [titanlabs-mc/battle-pass#621]
### Describe the bug

if you use these %total_progress% or %required_progress% as placeholders for other placeholders (for example, %formatter_text_length_{total_progress}% or %math_{total_progress}+1%), then the value of %total_progress% will not be read

in many plugins I use these functions with placeholders, but they don't work here, please fix it

### How to reproduce

[week1.zip](https://github.com/user-attachments/files/17835562/week1.zip)

**Comment by KPGTB** [comment]
Hey! I checked it and it seems that everything works great. You just incorrectly used total_progress placeholder. You should use `%total_progress%` Example `%formatter_text_length_%total_progress%%`
