### ISSUE TITLE
InventoryClickEvent for string "n"

### ISSUE THREAD

**Issue by bobhenl** [titanlabs-mc/battle-pass#623]
### Describe the bug

Hello, I got this error in console https://mcpaste.io/6a4b4ab169e9fc1c

### How to reproduce

Not really sure

### Server Log

https://mcpaste.io/6a4b4ab169e9fc1c

**Comment by KPGTB** [comment]
Hey! Can you send me configuration fo your menus?

**Comment by KPGTB** [comment]
closed due to no response
